### ISSUE TITLE
Discord Invite Link invalid

### ISSUE THREAD

**Issue by mspan** [mruderman/Rethinking-Fall-22-Group-Audit#1]
Hi!
When I try to use the invite link https://discord.gg/UqddWFT8 , it is rejected as expired or invalid. Thanks in advance!
- Mike
Update:  Feel free to close this issue. I did not realize that I already had access ... which I suspect was causing the (operator) error.

**Comment by mspan** [comment]
Update:  Feel free to close this issue. I did not realize that I already had access ... which I suspect was causing the (operator) error.

**Comment by mruderman** [comment]
No worries. Glad you got connected!
